### ISSUE TITLE
FEATURE: Collapse Summit and Saddle Analysis into a single function.

### ISSUE THREAD

**Issue by Marchowes** [Marchowes/pyProm#24]
Running IterateDiagonal() 1.x - 2.0 times is criminally inefficient. We are going to have to eliminate the shortcuts from summit analysis and implement a full neighborScan for finding valid Saddles. Sort of a bummer that that function needs to be handled in such a way, but whatcha going to do?.

**Comment by Marchowes** [comment]
This is going to require integration and trickery with the pond analysis as well.

**Comment by sambaldwin05** [comment]
@Marchowes Hey man, let me know if you want a hand with any of this stuff.  I use pretty much all of the tools you're using here in my daily work, so would be happy to help out in my (somewhat limited) spare time.  

Looks like a sweet tool you're building here! 👍

**Comment by Marchowes** [comment]
I probably don't need help, but contributions will not be frowned upon. Actually there are a few thing that I can do that will make providing help a lot easier.

Mainly, I need to write documentation. If I have time tonight I'm going to do a bunch of "renaming" of various objects (Islands, Ponds, etc are misleading names that need to be disposed of for more accurate names like "Plains" and "Enclaves").  Once that is done I can make some object diagrams to make it a little more clear whats going on. I've tried to comment code throughly, but there may be some confusion here and there.

The next big thing that needs to be done is Saddle analysis, which I mostly have in my head, tho I did write the comparison compressor. https://github.com/Marchowes/pyProm/blob/master/pyprom/lib/util.py#L45 Mostly its finding point/"blob" neighbors, comparing them, analyzing neighbor height patterns. and then running them through the above compressor.

But yeah, your comment will get me to dump more of whats in my head onto "paper".  This is a fun project.

**Comment by sambaldwin05** [comment]
Nice.  I definitely noticed the thorough commenting when I glanced through the code.

And I'm happy to contribute in whatever way you'd like me to, but for now I'll just try to get a dev environment up and running with my forked version of this repo.

Looking forward to playing with it, seems like fun stuff!

**Comment by Marchowes** [comment]
GDAL is probably the only thing that is going to give you any trouble.

I can give you some sample scripts and data to download later.

**Comment by Marchowes** [comment]
https://github.com/Marchowes/pyProm/pull/29
